apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30002
